nohup: ignoring input
Logging enabled at 
/home/luogang/SRC/NLP/LLM/build_graphrag_from_azure_AI_search/ragtest/output/202
40920-075055/reports/indexing-engine.log
/home/luogang/anaconda3/lib/python3.12/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
ðŸš€ create_base_text_units
                                   id  ... n_tokens
0    46bd59b6e97b4e48ab97bbd86aedb0e7  ...      917
1    11bd42485afa68bfbdc2c211a26e29c5  ...      777
2    9cfd79a45f62d79b481d2c23c00af4a2  ...      597
3    cf301d8bad7fbef9882f5fab55306d8d  ...     2609
4    709729aded007fde88009ea873ede812  ...     1113
..                                ...  ...      ...
243  e723f20f2dd7a8070e0ca8fc28e915fe  ...      597
244  f57b6aa7a78eeedb39e1bd7b66148998  ...     3012
245  32147ea4b3a4252ea7746286be0f4ccc  ...      575
246  feacba86d9128edb68770e5373565459  ...      628
247  b931e3ba58beb17c7244616d695bbc38  ...      640

[14938 rows x 5 columns]
Received signal 1, exiting...
â ‹ GraphRAG Indexer 
â”œâ”€â”€ Loading Input (InputFileType.text) - 14953 files loaded (15 filtered) 100%  
â”œâ”€â”€ create_base_text_units
â””â”€â”€ create_base_extracted_entities
    â””â”€â”€ Verb entity_extract                                  0% 17:11:53 0:02:50All tasks cancelled. Exiting...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/graphrag/index/__main__.py", line 104, in <module>
    index_cli(
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/graphrag/index/cli.py", line 163, in index_cli
    outputs = asyncio.run(
              ^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/graphrag/index/api.py", line 66, in build_index
    async for output in run_pipeline_with_config(
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/graphrag/index/run/run.py", line 126, in run_pipeline_with_config
    async for table in run_pipeline(
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/graphrag/index/run/run.py", line 227, in run_pipeline
    result = await _process_workflow(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/graphrag/index/run/workflow.py", line 91, in _process_workflow
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
    result = await result
             ^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/graphrag/index/verbs/entities/extraction/entity_extract.py", line 161, in entity_extract
    results = await derive_from_rows(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/datashaper/execution/derive_from_rows.py", line 33, in derive_from_rows
    return await derive_from_rows_asyncio_threads(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/datashaper/execution/derive_from_rows_asyncio_threads.py", line 40, in derive_from_rows_asyncio_threads
    return await derive_from_rows_base(input, transform, callbacks, gather)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/datashaper/execution/derive_from_rows_base.py", line 49, in derive_from_rows_base
    result = await gather(execute)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/datashaper/execution/derive_from_rows_asyncio_threads.py", line 38, in gather
    return await asyncio.gather(*[execute_task(task) for task in tasks])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luogang/anaconda3/lib/python3.12/site-packages/datashaper/execution/derive_from_rows_asyncio_threads.py", line 33, in execute_task
    async with semaphore:
  File "/home/luogang/anaconda3/lib/python3.12/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/home/luogang/anaconda3/lib/python3.12/asyncio/locks.py", line 386, in acquire
    await fut
asyncio.exceptions.CancelledError
sys:1: RuntimeWarning: coroutine 'to_thread' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
